require 'rake/testtask'
require 'rspec/core/rake_task'

Rake::TestTask.new do |t|
  t.test_files = FileList['test/test*.rb']
end

RSpec::Core::RakeTask.new do |t|
  t.pattern = 'spec/*_spec.rb'
end

task :default => [:test, :spec]
